/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaEstabelecimentos.java
 *
 * Created on 13/06/2011, 22:29:14
 */

package Projeto.Janelas;

/**
 *
 * @author Laerton
 */
public class JanelaEstabelecimentos extends javax.swing.JFrame {

    /** Creates new form JanelaEstabelecimentos */
    public JanelaEstabelecimentos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLEstabelecimento = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLpontos = new javax.swing.JLabel();
        jLpontos1 = new javax.swing.JLabel();
        jLpontos2 = new javax.swing.JLabel();
        jLpontos3 = new javax.swing.JLabel();
        jLpontos4 = new javax.swing.JLabel();
        jLpontos5 = new javax.swing.JLabel();
        jLpontos6 = new javax.swing.JLabel();
        jLpontos7 = new javax.swing.JLabel();
        jLpontos8 = new javax.swing.JLabel();
        jLpontos9 = new javax.swing.JLabel();
        jLpontos10 = new javax.swing.JLabel();
        jLpontos11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estabecimento:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLEstabelecimento.setText("jLabel2");
        jLEstabelecimento.setName("jLEstabelecimento"); // NOI18N

        jLEndereco.setText("jLabel2");
        jLEndereco.setName("jLEndereco"); // NOI18N

        jLabel4.setText("Endereço:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLTipo.setText("jLabel2");
        jLTipo.setName("jLTipo"); // NOI18N

        jLabel6.setText("Tipo de prato:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel8.setText("Classificação geral:");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("Pontos:");
        jLabel9.setName("jLabel9"); // NOI18N

        jLpontos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/-2.png"))); // NOI18N
        jLpontos.setText("0");
        jLpontos.setName("jLpontos"); // NOI18N

        jLpontos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/5.png"))); // NOI18N
        jLpontos1.setText("0");
        jLpontos1.setName("jLpontos1"); // NOI18N

        jLpontos2.setName("jLpontos2"); // NOI18N

        jLpontos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/2.png"))); // NOI18N
        jLpontos3.setText("0");
        jLpontos3.setName("jLpontos3"); // NOI18N

        jLpontos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/0.png"))); // NOI18N
        jLpontos4.setText("0");
        jLpontos4.setName("jLpontos4"); // NOI18N

        jLpontos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/-3.png"))); // NOI18N
        jLpontos5.setText("0");
        jLpontos5.setName("jLpontos5"); // NOI18N

        jLpontos6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/-4.png"))); // NOI18N
        jLpontos6.setText("0");
        jLpontos6.setName("jLpontos6"); // NOI18N

        jLpontos7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/3.png"))); // NOI18N
        jLpontos7.setText("0");
        jLpontos7.setName("jLpontos7"); // NOI18N

        jLpontos8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/-1.png"))); // NOI18N
        jLpontos8.setText("0");
        jLpontos8.setName("jLpontos8"); // NOI18N

        jLpontos9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/4.png"))); // NOI18N
        jLpontos9.setText("0");
        jLpontos9.setName("jLpontos9"); // NOI18N

        jLpontos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/1.png"))); // NOI18N
        jLpontos10.setText("0");
        jLpontos10.setName("jLpontos10"); // NOI18N

        jLpontos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Icones/32/-5.png"))); // NOI18N
        jLpontos11.setText("0");
        jLpontos11.setName("jLpontos11"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLpontos1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLpontos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLpontos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(524, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLEstabelecimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLpontos9)
                        .addComponent(jLpontos7)
                        .addComponent(jLpontos3)
                        .addComponent(jLpontos10)
                        .addComponent(jLpontos4)
                        .addComponent(jLpontos8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLpontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLpontos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLpontos6)
                        .addComponent(jLpontos11))
                    .addComponent(jLpontos1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(106, Short.MAX_VALUE)
                    .addComponent(jLpontos2)
                    .addGap(57, 57, 57)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEstabelecimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLEstabelecimento;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLpontos;
    private javax.swing.JLabel jLpontos1;
    private javax.swing.JLabel jLpontos10;
    private javax.swing.JLabel jLpontos11;
    private javax.swing.JLabel jLpontos2;
    private javax.swing.JLabel jLpontos3;
    private javax.swing.JLabel jLpontos4;
    private javax.swing.JLabel jLpontos5;
    private javax.swing.JLabel jLpontos6;
    private javax.swing.JLabel jLpontos7;
    private javax.swing.JLabel jLpontos8;
    private javax.swing.JLabel jLpontos9;
    // End of variables declaration//GEN-END:variables

}
